// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/pb/agent/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Ping_FullMethodName             = "/chv.agent.v1.AgentService/Ping"
	AgentService_ReportNodeStatus_FullMethodName = "/chv.agent.v1.AgentService/ReportNodeStatus"
	AgentService_ValidateNode_FullMethodName     = "/chv.agent.v1.AgentService/ValidateNode"
	AgentService_EnsureBridge_FullMethodName     = "/chv.agent.v1.AgentService/EnsureBridge"
	AgentService_ImportImage_FullMethodName      = "/chv.agent.v1.AgentService/ImportImage"
	AgentService_CreateVolume_FullMethodName     = "/chv.agent.v1.AgentService/CreateVolume"
	AgentService_ResizeVolume_FullMethodName     = "/chv.agent.v1.AgentService/ResizeVolume"
	AgentService_DeleteVolume_FullMethodName     = "/chv.agent.v1.AgentService/DeleteVolume"
	AgentService_ProvisionVM_FullMethodName      = "/chv.agent.v1.AgentService/ProvisionVM"
	AgentService_StartVM_FullMethodName          = "/chv.agent.v1.AgentService/StartVM"
	AgentService_StopVM_FullMethodName           = "/chv.agent.v1.AgentService/StopVM"
	AgentService_RebootVM_FullMethodName         = "/chv.agent.v1.AgentService/RebootVM"
	AgentService_DeleteVM_FullMethodName         = "/chv.agent.v1.AgentService/DeleteVM"
	AgentService_GetVMState_FullMethodName       = "/chv.agent.v1.AgentService/GetVMState"
	AgentService_ListHostVMs_FullMethodName      = "/chv.agent.v1.AgentService/ListHostVMs"
	AgentService_PrepareDrain_FullMethodName     = "/chv.agent.v1.AgentService/PrepareDrain"
	AgentService_StreamConsole_FullMethodName    = "/chv.agent.v1.AgentService/StreamConsole"
	AgentService_GetConsoleStatus_FullMethodName = "/chv.agent.v1.AgentService/GetConsoleStatus"
	AgentService_CloseConsole_FullMethodName     = "/chv.agent.v1.AgentService/CloseConsole"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent service definition
type AgentServiceClient interface {
	// Health check
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
	// Node status reporting
	ReportNodeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error)
	// Node validation
	ValidateNode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	// Bridge management
	EnsureBridge(ctx context.Context, in *EnsureBridgeRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	// Image management
	ImportImage(ctx context.Context, in *ImageImportRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	// Volume management
	CreateVolume(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	ResizeVolume(ctx context.Context, in *VolumeResizeRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	DeleteVolume(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	// VM lifecycle
	ProvisionVM(ctx context.Context, in *ProvisionVMRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	StartVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	StopVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	RebootVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	DeleteVM(ctx context.Context, in *VMDeleteRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	GetVMState(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	ListHostVMs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListVMsResponse, error)
	// Maintenance
	PrepareDrain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
	// Console streaming
	StreamConsole(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsoleStreamRequest, ConsoleStreamResponse], error)
	GetConsoleStatus(ctx context.Context, in *ConsoleStatusRequest, opts ...grpc.CallOption) (*ConsoleStatusResponse, error)
	CloseConsole(ctx context.Context, in *ConsoleCloseRequest, opts ...grpc.CallOption) (*ConsoleCloseResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportNodeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, AgentService_ReportNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ValidateNode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, AgentService_ValidateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) EnsureBridge(ctx context.Context, in *EnsureBridgeRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, AgentService_EnsureBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ImportImage(ctx context.Context, in *ImageImportRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, AgentService_ImportImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateVolume(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ResizeVolume(ctx context.Context, in *VolumeResizeRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, AgentService_ResizeVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteVolume(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ProvisionVM(ctx context.Context, in *ProvisionVMRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, AgentService_ProvisionVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, AgentService_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, AgentService_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RebootVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, AgentService_RebootVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteVM(ctx context.Context, in *VMDeleteRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetVMState(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, AgentService_GetVMState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListHostVMs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListHostVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PrepareDrain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, AgentService_PrepareDrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamConsole(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsoleStreamRequest, ConsoleStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamConsole_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsoleStreamRequest, ConsoleStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamConsoleClient = grpc.BidiStreamingClient[ConsoleStreamRequest, ConsoleStreamResponse]

func (c *agentServiceClient) GetConsoleStatus(ctx context.Context, in *ConsoleStatusRequest, opts ...grpc.CallOption) (*ConsoleStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_GetConsoleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CloseConsole(ctx context.Context, in *ConsoleCloseRequest, opts ...grpc.CallOption) (*ConsoleCloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleCloseResponse)
	err := c.cc.Invoke(ctx, AgentService_CloseConsole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// Agent service definition
type AgentServiceServer interface {
	// Health check
	Ping(context.Context, *Empty) (*PingResponse, error)
	// Node status reporting
	ReportNodeStatus(context.Context, *Empty) (*NodeStatus, error)
	// Node validation
	ValidateNode(context.Context, *Empty) (*NodeValidateResponse, error)
	// Bridge management
	EnsureBridge(context.Context, *EnsureBridgeRequest) (*NodeValidateResponse, error)
	// Image management
	ImportImage(context.Context, *ImageImportRequest) (*NodeValidateResponse, error)
	// Volume management
	CreateVolume(context.Context, *VolumeCreateRequest) (*NodeValidateResponse, error)
	ResizeVolume(context.Context, *VolumeResizeRequest) (*NodeValidateResponse, error)
	DeleteVolume(context.Context, *VolumeCreateRequest) (*NodeValidateResponse, error)
	// VM lifecycle
	ProvisionVM(context.Context, *ProvisionVMRequest) (*VMStateResponse, error)
	StartVM(context.Context, *VMStateRequest) (*VMStateResponse, error)
	StopVM(context.Context, *VMStateRequest) (*VMStateResponse, error)
	RebootVM(context.Context, *VMStateRequest) (*VMStateResponse, error)
	DeleteVM(context.Context, *VMDeleteRequest) (*VMStateResponse, error)
	GetVMState(context.Context, *VMStateRequest) (*VMStateResponse, error)
	ListHostVMs(context.Context, *Empty) (*ListVMsResponse, error)
	// Maintenance
	PrepareDrain(context.Context, *DrainRequest) (*DrainResponse, error)
	// Console streaming
	StreamConsole(grpc.BidiStreamingServer[ConsoleStreamRequest, ConsoleStreamResponse]) error
	GetConsoleStatus(context.Context, *ConsoleStatusRequest) (*ConsoleStatusResponse, error)
	CloseConsole(context.Context, *ConsoleCloseRequest) (*ConsoleCloseResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Ping(context.Context, *Empty) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) ReportNodeStatus(context.Context, *Empty) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportNodeStatus not implemented")
}
func (UnimplementedAgentServiceServer) ValidateNode(context.Context, *Empty) (*NodeValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateNode not implemented")
}
func (UnimplementedAgentServiceServer) EnsureBridge(context.Context, *EnsureBridgeRequest) (*NodeValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureBridge not implemented")
}
func (UnimplementedAgentServiceServer) ImportImage(context.Context, *ImageImportRequest) (*NodeValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportImage not implemented")
}
func (UnimplementedAgentServiceServer) CreateVolume(context.Context, *VolumeCreateRequest) (*NodeValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedAgentServiceServer) ResizeVolume(context.Context, *VolumeResizeRequest) (*NodeValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeVolume not implemented")
}
func (UnimplementedAgentServiceServer) DeleteVolume(context.Context, *VolumeCreateRequest) (*NodeValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedAgentServiceServer) ProvisionVM(context.Context, *ProvisionVMRequest) (*VMStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionVM not implemented")
}
func (UnimplementedAgentServiceServer) StartVM(context.Context, *VMStateRequest) (*VMStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedAgentServiceServer) StopVM(context.Context, *VMStateRequest) (*VMStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedAgentServiceServer) RebootVM(context.Context, *VMStateRequest) (*VMStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebootVM not implemented")
}
func (UnimplementedAgentServiceServer) DeleteVM(context.Context, *VMDeleteRequest) (*VMStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedAgentServiceServer) GetVMState(context.Context, *VMStateRequest) (*VMStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMState not implemented")
}
func (UnimplementedAgentServiceServer) ListHostVMs(context.Context, *Empty) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHostVMs not implemented")
}
func (UnimplementedAgentServiceServer) PrepareDrain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareDrain not implemented")
}
func (UnimplementedAgentServiceServer) StreamConsole(grpc.BidiStreamingServer[ConsoleStreamRequest, ConsoleStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamConsole not implemented")
}
func (UnimplementedAgentServiceServer) GetConsoleStatus(context.Context, *ConsoleStatusRequest) (*ConsoleStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsoleStatus not implemented")
}
func (UnimplementedAgentServiceServer) CloseConsole(context.Context, *ConsoleCloseRequest) (*ConsoleCloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseConsole not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportNodeStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ValidateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ValidateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ValidateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ValidateNode(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_EnsureBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).EnsureBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_EnsureBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).EnsureBridge(ctx, req.(*EnsureBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ImportImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ImportImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ImportImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ImportImage(ctx, req.(*ImageImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateVolume(ctx, req.(*VolumeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ResizeVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ResizeVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ResizeVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ResizeVolume(ctx, req.(*VolumeResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteVolume(ctx, req.(*VolumeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ProvisionVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ProvisionVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ProvisionVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ProvisionVM(ctx, req.(*ProvisionVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartVM(ctx, req.(*VMStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopVM(ctx, req.(*VMStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RebootVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RebootVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RebootVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RebootVM(ctx, req.(*VMStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteVM(ctx, req.(*VMDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetVMState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetVMState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetVMState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetVMState(ctx, req.(*VMStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListHostVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListHostVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListHostVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListHostVMs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PrepareDrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PrepareDrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PrepareDrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PrepareDrain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamConsole_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).StreamConsole(&grpc.GenericServerStream[ConsoleStreamRequest, ConsoleStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamConsoleServer = grpc.BidiStreamingServer[ConsoleStreamRequest, ConsoleStreamResponse]

func _AgentService_GetConsoleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsoleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetConsoleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetConsoleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetConsoleStatus(ctx, req.(*ConsoleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CloseConsole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsoleCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CloseConsole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CloseConsole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CloseConsole(ctx, req.(*ConsoleCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chv.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AgentService_Ping_Handler,
		},
		{
			MethodName: "ReportNodeStatus",
			Handler:    _AgentService_ReportNodeStatus_Handler,
		},
		{
			MethodName: "ValidateNode",
			Handler:    _AgentService_ValidateNode_Handler,
		},
		{
			MethodName: "EnsureBridge",
			Handler:    _AgentService_EnsureBridge_Handler,
		},
		{
			MethodName: "ImportImage",
			Handler:    _AgentService_ImportImage_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _AgentService_CreateVolume_Handler,
		},
		{
			MethodName: "ResizeVolume",
			Handler:    _AgentService_ResizeVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _AgentService_DeleteVolume_Handler,
		},
		{
			MethodName: "ProvisionVM",
			Handler:    _AgentService_ProvisionVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _AgentService_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _AgentService_StopVM_Handler,
		},
		{
			MethodName: "RebootVM",
			Handler:    _AgentService_RebootVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _AgentService_DeleteVM_Handler,
		},
		{
			MethodName: "GetVMState",
			Handler:    _AgentService_GetVMState_Handler,
		},
		{
			MethodName: "ListHostVMs",
			Handler:    _AgentService_ListHostVMs_Handler,
		},
		{
			MethodName: "PrepareDrain",
			Handler:    _AgentService_PrepareDrain_Handler,
		},
		{
			MethodName: "GetConsoleStatus",
			Handler:    _AgentService_GetConsoleStatus_Handler,
		},
		{
			MethodName: "CloseConsole",
			Handler:    _AgentService_CloseConsole_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConsole",
			Handler:       _AgentService_StreamConsole_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/pb/agent/agent.proto",
}
