// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub for the agent protocol.

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Empty is an empty message.
type Empty struct{}

// ErrorDetail represents a structured error.
type ErrorDetail struct {
	Code      string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable bool   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Hint      string `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
}

// NodeCapability represents a node capability.
type NodeCapability struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

// NodeStatus represents node status.
type NodeStatus struct {
	NodeId              string            `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname            string            `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	State               string            `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	TotalCpuCores       uint32            `protobuf:"varint,4,opt,name=total_cpu_cores,json=totalCpuCores,proto3" json:"total_cpu_cores,omitempty"`
	TotalRamMb          uint64            `protobuf:"varint,5,opt,name=total_ram_mb,json=totalRamMb,proto3" json:"total_ram_mb,omitempty"`
	AllocatableCpuCores uint32            `protobuf:"varint,6,opt,name=allocatable_cpu_cores,json=allocatableCpuCores,proto3" json:"allocatable_cpu_cores,omitempty"`
	AllocatableRamMb    uint64            `protobuf:"varint,7,opt,name=allocatable_ram_mb,json=allocatableRamMb,proto3" json:"allocatable_ram_mb,omitempty"`
	Capabilities        []*NodeCapability `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	AgentVersion        string            `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	HypervisorVersion   string            `protobuf:"bytes,10,opt,name=hypervisor_version,json=hypervisorVersion,proto3" json:"hypervisor_version,omitempty"`
	LastHeartbeatUnix   int64             `protobuf:"varint,11,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
}

// PingResponse is the response to Ping.
type PingResponse struct {
	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

// EnsureBridgeRequest requests bridge creation.
type EnsureBridgeRequest struct {
	BridgeName string `protobuf:"bytes,1,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`
	Mtu        uint32 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

// ImageImportRequest requests image import.
type ImageImportRequest struct {
	ImageId          string `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	SourceUrl        string `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	SourceFormat     string `protobuf:"bytes,3,opt,name=source_format,json=sourceFormat,proto3" json:"source_format,omitempty"`
	NormalizedFormat string `protobuf:"bytes,4,opt,name=normalized_format,json=normalizedFormat,proto3" json:"normalized_format,omitempty"`
	Checksum         string `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

// VolumeCreateRequest requests volume creation.
type VolumeCreateRequest struct {
	VolumeId         string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	PoolId           string `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	PoolPath         string `protobuf:"bytes,3,opt,name=pool_path,json=poolPath,proto3" json:"pool_path,omitempty"`
	Format           string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	SizeBytes        uint64 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	BackingImageId   string `protobuf:"bytes,6,opt,name=backing_image_id,json=backingImageId,proto3" json:"backing_image_id,omitempty"`
	BackingImagePath string `protobuf:"bytes,7,opt,name=backing_image_path,json=backingImagePath,proto3" json:"backing_image_path,omitempty"`
}

// VolumeResizeRequest requests volume resize.
type VolumeResizeRequest struct {
	VolumeId     string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	PoolPath     string `protobuf:"bytes,2,opt,name=pool_path,json=poolPath,proto3" json:"pool_path,omitempty"`
	NewSizeBytes uint64 `protobuf:"varint,3,opt,name=new_size_bytes,json=newSizeBytes,proto3" json:"new_size_bytes,omitempty"`
}

// NetworkAttachment represents a network attachment.
type NetworkAttachment struct {
	NetworkId  string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	BridgeName string `protobuf:"bytes,2,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`
	MacAddress string `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress  string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Dhcp       bool   `protobuf:"varint,5,opt,name=dhcp,proto3" json:"dhcp,omitempty"`
}

// DiskAttachment represents a disk attachment.
type DiskAttachment struct {
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Path     string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Bus      string `protobuf:"bytes,3,opt,name=bus,proto3" json:"bus,omitempty"`
	Boot     bool   `protobuf:"varint,4,opt,name=boot,proto3" json:"boot,omitempty"`
	Readonly bool   `protobuf:"varint,5,opt,name=readonly,proto3" json:"readonly,omitempty"`
}

// BootSpec represents boot configuration.
type BootSpec struct {
	Mode           string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	KernelPath     string `protobuf:"bytes,2,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	InitrdPath     string `protobuf:"bytes,3,opt,name=initrd_path,json=initrdPath,proto3" json:"initrd_path,omitempty"`
	Cmdline        string `protobuf:"bytes,4,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	FirmwarePath   string `protobuf:"bytes,5,opt,name=firmware_path,json=firmwarePath,proto3" json:"firmware_path,omitempty"`
	BackingImageId string `protobuf:"bytes,6,opt,name=backing_image_id,json=backingImageId,proto3" json:"backing_image_id,omitempty"`
}

// CloudInitSpec represents cloud-init configuration.
type CloudInitSpec struct {
	UserData      string `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	MetaData      string `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	NetworkConfig string `protobuf:"bytes,3,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"`
}

// ProvisionVMRequest requests VM provisioning.
type ProvisionVMRequest struct {
	VmId      string               `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName    string               `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Vcpu      uint32               `protobuf:"varint,3,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryMb  uint64               `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Boot      *BootSpec            `protobuf:"bytes,5,opt,name=boot,proto3" json:"boot,omitempty"`
	Disks     []*DiskAttachment    `protobuf:"bytes,6,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks  []*NetworkAttachment `protobuf:"bytes,7,rep,name=networks,proto3" json:"networks,omitempty"`
	CloudInit *CloudInitSpec       `protobuf:"bytes,8,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"`
}

// VMStateRequest requests VM state.
type VMStateRequest struct {
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
}

// VMStateResponse is the VM state response.
type VMStateResponse struct {
	VmId  string       `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State string       `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid   string       `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Error *ErrorDetail `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

// VMDeleteRequest requests VM deletion.
type VMDeleteRequest struct {
	VmId          string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	DeleteVolumes bool   `protobuf:"varint,2,opt,name=delete_volumes,json=deleteVolumes,proto3" json:"delete_volumes,omitempty"`
	Force         bool   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
}

// NodeValidateResponse is the node validation response.
type NodeValidateResponse struct {
	Ok     bool           `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Errors []*ErrorDetail `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

// DrainRequest requests drain mode.
type DrainRequest struct {
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Force  bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
}

// DrainResponse is the drain response.
type DrainResponse struct {
	Ok        bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ActiveVms []string     `protobuf:"bytes,2,rep,name=active_vms,json=activeVms,proto3" json:"active_vms,omitempty"`
	Error     *ErrorDetail `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

// ListVMsResponse is the list VMs response.
type ListVMsResponse struct {
	Vms []*ListVMsResponse_VMInfo `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
}

// VMInfo represents VM info.
type ListVMsResponse_VMInfo struct {
	VmId     string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State    string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid      string `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Vcpu     uint32 `protobuf:"varint,4,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryMb uint64 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
}

// ConsoleStreamRequest represents a console stream request.
type ConsoleStreamRequest struct {
	Type ConsoleStreamRequest_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=agent.ConsoleStreamRequest_MessageType" json:"type,omitempty"`
	VmId string                           `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Data []byte                           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Rows uint32                           `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32                           `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`
	Token string                          `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

// ConsoleStreamRequest_MessageType represents message types.
type ConsoleStreamRequest_MessageType int32

const (
	ConsoleStreamRequest_UNKNOWN ConsoleStreamRequest_MessageType = 0
	ConsoleStreamRequest_INPUT   ConsoleStreamRequest_MessageType = 1
	ConsoleStreamRequest_RESIZE  ConsoleStreamRequest_MessageType = 2
	ConsoleStreamRequest_PING    ConsoleStreamRequest_MessageType = 3
)

// GetVmId returns the VM ID.
func (x *ConsoleStreamRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// GetType returns the message type.
func (x *ConsoleStreamRequest) GetType() ConsoleStreamRequest_MessageType {
	if x != nil {
		return x.Type
	}
	return ConsoleStreamRequest_UNKNOWN
}

// GetData returns the data.
func (x *ConsoleStreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConsoleStreamResponse represents a console stream response.
type ConsoleStreamResponse struct {
	Type      ConsoleStreamResponse_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=agent.ConsoleStreamResponse_MessageType" json:"type,omitempty"`
	Data      []byte                            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message   string                            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp int64                             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

// ConsoleStreamResponse_MessageType represents message types.
type ConsoleStreamResponse_MessageType int32

const (
	ConsoleStreamResponse_UNKNOWN ConsoleStreamResponse_MessageType = 0
	ConsoleStreamResponse_OUTPUT  ConsoleStreamResponse_MessageType = 1
	ConsoleStreamResponse_ERROR   ConsoleStreamResponse_MessageType = 2
	ConsoleStreamResponse_STATUS  ConsoleStreamResponse_MessageType = 3
	ConsoleStreamResponse_HISTORY ConsoleStreamResponse_MessageType = 4
)

// GetType returns the message type.
func (x *ConsoleStreamResponse) GetType() ConsoleStreamResponse_MessageType {
	if x != nil {
		return x.Type
	}
	return ConsoleStreamResponse_UNKNOWN
}

// GetData returns the data.
func (x *ConsoleStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetMessage returns the message.
func (x *ConsoleStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ConsoleStatusRequest requests console status.
type ConsoleStatusRequest struct {
	VmId string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
}

// GetVmId returns the VM ID.
func (x *ConsoleStatusRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// ConsoleStatusResponse is the console status response.
type ConsoleStatusResponse struct {
	VmId        string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Active      bool   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Connected   bool   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	ClientCount int32  `protobuf:"varint,4,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	LogPath     string `protobuf:"bytes,5,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	TtyEnabled  bool   `protobuf:"varint,6,opt,name=tty_enabled,json=ttyEnabled,proto3" json:"tty_enabled,omitempty"`
}

// GetVmId returns the VM ID.
func (x *ConsoleStatusResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// ConsoleCloseRequest requests console close.
type ConsoleCloseRequest struct {
	VmId  string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Force bool   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
}

// GetVmId returns the VM ID.
func (x *ConsoleCloseRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// ConsoleCloseResponse is the console close response.
type ConsoleCloseResponse struct {
	VmId   string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Closed bool   `protobuf:"varint,2,opt,name=closed,proto3" json:"closed,omitempty"`
}

// AgentService_StreamConsoleServer is the server interface for streaming.
type AgentService_StreamConsoleServer interface {
	grpc.ServerStream
	Send(*ConsoleStreamResponse) error
	Recv() (*ConsoleStreamRequest, error)
}

type agentServiceStreamConsoleServer struct {
	grpc.ServerStream
}

func (x *agentServiceStreamConsoleServer) Send(m *ConsoleStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceStreamConsoleServer) Recv() (*ConsoleStreamRequest, error) {
	m := new(ConsoleStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	Ping(context.Context, *Empty) (*PingResponse, error)
	ReportNodeStatus(context.Context, *Empty) (*NodeStatus, error)
	ValidateNode(context.Context, *Empty) (*NodeValidateResponse, error)
	EnsureBridge(context.Context, *EnsureBridgeRequest) (*NodeValidateResponse, error)
	ImportImage(context.Context, *ImageImportRequest) (*NodeValidateResponse, error)
	CreateVolume(context.Context, *VolumeCreateRequest) (*NodeValidateResponse, error)
	ResizeVolume(context.Context, *VolumeResizeRequest) (*NodeValidateResponse, error)
	ProvisionVM(context.Context, *ProvisionVMRequest) (*VMStateResponse, error)
	StartVM(context.Context, *VMStateRequest) (*VMStateResponse, error)
	StopVM(context.Context, *VMStateRequest) (*VMStateResponse, error)
	RebootVM(context.Context, *VMStateRequest) (*VMStateResponse, error)
	DeleteVM(context.Context, *VMDeleteRequest) (*VMStateResponse, error)
	GetVMState(context.Context, *VMStateRequest) (*VMStateResponse, error)
	ListHostVMs(context.Context, *Empty) (*ListVMsResponse, error)
	PrepareDrain(context.Context, *DrainRequest) (*DrainResponse, error)
	StreamConsole(AgentService_StreamConsoleServer) error
	GetConsoleStatus(context.Context, *ConsoleStatusRequest) (*ConsoleStatusResponse, error)
	CloseConsole(context.Context, *ConsoleCloseRequest) (*ConsoleCloseResponse, error)
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Ping(context.Context, *Empty) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) ReportNodeStatus(context.Context, *Empty) (*NodeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportNodeStatus not implemented")
}
func (UnimplementedAgentServiceServer) ValidateNode(context.Context, *Empty) (*NodeValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateNode not implemented")
}
func (UnimplementedAgentServiceServer) EnsureBridge(context.Context, *EnsureBridgeRequest) (*NodeValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureBridge not implemented")
}
func (UnimplementedAgentServiceServer) ImportImage(context.Context, *ImageImportRequest) (*NodeValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportImage not implemented")
}
func (UnimplementedAgentServiceServer) CreateVolume(context.Context, *VolumeCreateRequest) (*NodeValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedAgentServiceServer) ResizeVolume(context.Context, *VolumeResizeRequest) (*NodeValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizeVolume not implemented")
}
func (UnimplementedAgentServiceServer) ProvisionVM(context.Context, *ProvisionVMRequest) (*VMStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionVM not implemented")
}
func (UnimplementedAgentServiceServer) StartVM(context.Context, *VMStateRequest) (*VMStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedAgentServiceServer) StopVM(context.Context, *VMStateRequest) (*VMStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedAgentServiceServer) RebootVM(context.Context, *VMStateRequest) (*VMStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebootVM not implemented")
}
func (UnimplementedAgentServiceServer) DeleteVM(context.Context, *VMDeleteRequest) (*VMStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedAgentServiceServer) GetVMState(context.Context, *VMStateRequest) (*VMStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVMState not implemented")
}
func (UnimplementedAgentServiceServer) ListHostVMs(context.Context, *Empty) (*ListVMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHostVMs not implemented")
}
func (UnimplementedAgentServiceServer) PrepareDrain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareDrain not implemented")
}
func (UnimplementedAgentServiceServer) StreamConsole(AgentService_StreamConsoleServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamConsole not implemented")
}
func (UnimplementedAgentServiceServer) GetConsoleStatus(context.Context, *ConsoleStatusRequest) (*ConsoleStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsoleStatus not implemented")
}
func (UnimplementedAgentServiceServer) CloseConsole(context.Context, *ConsoleCloseRequest) (*ConsoleCloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseConsole not implemented")
}

// RegisterAgentServiceServer registers the server.
func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Ping", Handler: nil},
		{MethodName: "ReportNodeStatus", Handler: nil},
		{MethodName: "ValidateNode", Handler: nil},
		{MethodName: "EnsureBridge", Handler: nil},
		{MethodName: "ImportImage", Handler: nil},
		{MethodName: "CreateVolume", Handler: nil},
		{MethodName: "ResizeVolume", Handler: nil},
		{MethodName: "ProvisionVM", Handler: nil},
		{MethodName: "StartVM", Handler: nil},
		{MethodName: "StopVM", Handler: nil},
		{MethodName: "RebootVM", Handler: nil},
		{MethodName: "DeleteVM", Handler: nil},
		{MethodName: "GetVMState", Handler: nil},
		{MethodName: "ListHostVMs", Handler: nil},
		{MethodName: "PrepareDrain", Handler: nil},
		{MethodName: "GetConsoleStatus", Handler: nil},
		{MethodName: "CloseConsole", Handler: nil},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConsole",
			Handler:       nil,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}

// AgentServiceClient is the client interface.
type AgentServiceClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
	ReportNodeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error)
	ValidateNode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	EnsureBridge(ctx context.Context, in *EnsureBridgeRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	ImportImage(ctx context.Context, in *ImageImportRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	CreateVolume(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	ResizeVolume(ctx context.Context, in *VolumeResizeRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error)
	ProvisionVM(ctx context.Context, in *ProvisionVMRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	StartVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	StopVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	RebootVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	DeleteVM(ctx context.Context, in *VMDeleteRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	GetVMState(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error)
	ListHostVMs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListVMsResponse, error)
	PrepareDrain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
	StreamConsole(ctx context.Context, opts ...grpc.CallOption) (AgentService_StreamConsoleClient, error)
	GetConsoleStatus(ctx context.Context, in *ConsoleStatusRequest, opts ...grpc.CallOption) (*ConsoleStatusResponse, error)
	CloseConsole(ctx context.Context, in *ConsoleCloseRequest, opts ...grpc.CallOption) (*ConsoleCloseResponse, error)
}

// AgentService_StreamConsoleClient is the client interface for streaming.
type AgentService_StreamConsoleClient interface {
	grpc.ClientStream
	Send(*ConsoleStreamRequest) error
	Recv() (*ConsoleStreamResponse, error)
}

type agentServiceStreamConsoleClient struct {
	grpc.ClientStream
}

func (x *agentServiceStreamConsoleClient) Send(m *ConsoleStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceStreamConsoleClient) Recv() (*ConsoleStreamResponse, error) {
	m := new(ConsoleStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewAgentServiceClient creates a new client.
func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func (c *agentServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportNodeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, "/agent.AgentService/ReportNodeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ValidateNode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/ValidateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) EnsureBridge(ctx context.Context, in *EnsureBridgeRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/EnsureBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ImportImage(ctx context.Context, in *ImageImportRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/ImportImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateVolume(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/CreateVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ResizeVolume(ctx context.Context, in *VolumeResizeRequest, opts ...grpc.CallOption) (*NodeValidateResponse, error) {
	out := new(NodeValidateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/ResizeVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ProvisionVM(ctx context.Context, in *ProvisionVMRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/ProvisionVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/StartVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/StopVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RebootVM(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/RebootVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteVM(ctx context.Context, in *VMDeleteRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/DeleteVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetVMState(ctx context.Context, in *VMStateRequest, opts ...grpc.CallOption) (*VMStateResponse, error) {
	out := new(VMStateResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetVMState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListHostVMs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/ListHostVMs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PrepareDrain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/PrepareDrain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamConsole(ctx context.Context, opts ...grpc.CallOption) (AgentService_StreamConsoleClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], "/agent.AgentService/StreamConsole", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceStreamConsoleClient{stream}
	return x, nil
}

func (c *agentServiceClient) GetConsoleStatus(ctx context.Context, in *ConsoleStatusRequest, opts ...grpc.CallOption) (*ConsoleStatusResponse, error) {
	out := new(ConsoleStatusResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetConsoleStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CloseConsole(ctx context.Context, in *ConsoleCloseRequest, opts ...grpc.CallOption) (*ConsoleCloseResponse, error) {
	out := new(ConsoleCloseResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/CloseConsole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
