// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/pb/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsoleStreamRequest_MessageType int32

const (
	ConsoleStreamRequest_UNKNOWN ConsoleStreamRequest_MessageType = 0
	ConsoleStreamRequest_INPUT   ConsoleStreamRequest_MessageType = 1 // Client input to VM
	ConsoleStreamRequest_RESIZE  ConsoleStreamRequest_MessageType = 2 // Terminal resize
	ConsoleStreamRequest_PING    ConsoleStreamRequest_MessageType = 3 // Keepalive ping
)

// Enum value maps for ConsoleStreamRequest_MessageType.
var (
	ConsoleStreamRequest_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "INPUT",
		2: "RESIZE",
		3: "PING",
	}
	ConsoleStreamRequest_MessageType_value = map[string]int32{
		"UNKNOWN": 0,
		"INPUT":   1,
		"RESIZE":  2,
		"PING":    3,
	}
)

func (x ConsoleStreamRequest_MessageType) Enum() *ConsoleStreamRequest_MessageType {
	p := new(ConsoleStreamRequest_MessageType)
	*p = x
	return p
}

func (x ConsoleStreamRequest_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleStreamRequest_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_agent_agent_proto_enumTypes[0].Descriptor()
}

func (ConsoleStreamRequest_MessageType) Type() protoreflect.EnumType {
	return &file_internal_pb_agent_agent_proto_enumTypes[0]
}

func (x ConsoleStreamRequest_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleStreamRequest_MessageType.Descriptor instead.
func (ConsoleStreamRequest_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{21, 0}
}

type ConsoleStreamResponse_MessageType int32

const (
	ConsoleStreamResponse_UNKNOWN ConsoleStreamResponse_MessageType = 0
	ConsoleStreamResponse_OUTPUT  ConsoleStreamResponse_MessageType = 1 // VM output
	ConsoleStreamResponse_ERROR   ConsoleStreamResponse_MessageType = 2 // Error message
	ConsoleStreamResponse_STATUS  ConsoleStreamResponse_MessageType = 3 // Status message
	ConsoleStreamResponse_HISTORY ConsoleStreamResponse_MessageType = 4 // Initial history buffer
)

// Enum value maps for ConsoleStreamResponse_MessageType.
var (
	ConsoleStreamResponse_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "OUTPUT",
		2: "ERROR",
		3: "STATUS",
		4: "HISTORY",
	}
	ConsoleStreamResponse_MessageType_value = map[string]int32{
		"UNKNOWN": 0,
		"OUTPUT":  1,
		"ERROR":   2,
		"STATUS":  3,
		"HISTORY": 4,
	}
)

func (x ConsoleStreamResponse_MessageType) Enum() *ConsoleStreamResponse_MessageType {
	p := new(ConsoleStreamResponse_MessageType)
	*p = x
	return p
}

func (x ConsoleStreamResponse_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleStreamResponse_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_agent_agent_proto_enumTypes[1].Descriptor()
}

func (ConsoleStreamResponse_MessageType) Type() protoreflect.EnumType {
	return &file_internal_pb_agent_agent_proto_enumTypes[1]
}

func (x ConsoleStreamResponse_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleStreamResponse_MessageType.Descriptor instead.
func (ConsoleStreamResponse_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{22, 0}
}

// Empty message for methods without request/response
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{0}
}

// Structured error details
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorDetail) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

// Node capability key-value pair
type NodeCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapability) Reset() {
	*x = NodeCapability{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapability) ProtoMessage() {}

func (x *NodeCapability) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapability.ProtoReflect.Descriptor instead.
func (*NodeCapability) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *NodeCapability) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NodeCapability) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Node status reported by agent
type NodeStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeId              string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname            string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	State               string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	TotalCpuCores       uint32                 `protobuf:"varint,4,opt,name=total_cpu_cores,json=totalCpuCores,proto3" json:"total_cpu_cores,omitempty"`
	TotalRamMb          uint64                 `protobuf:"varint,5,opt,name=total_ram_mb,json=totalRamMb,proto3" json:"total_ram_mb,omitempty"`
	AllocatableCpuCores uint32                 `protobuf:"varint,6,opt,name=allocatable_cpu_cores,json=allocatableCpuCores,proto3" json:"allocatable_cpu_cores,omitempty"`
	AllocatableRamMb    uint64                 `protobuf:"varint,7,opt,name=allocatable_ram_mb,json=allocatableRamMb,proto3" json:"allocatable_ram_mb,omitempty"`
	Capabilities        []*NodeCapability      `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	AgentVersion        string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	HypervisorVersion   string                 `protobuf:"bytes,10,opt,name=hypervisor_version,json=hypervisorVersion,proto3" json:"hypervisor_version,omitempty"`
	LastHeartbeatUnix   int64                  `protobuf:"varint,11,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeStatus) GetTotalCpuCores() uint32 {
	if x != nil {
		return x.TotalCpuCores
	}
	return 0
}

func (x *NodeStatus) GetTotalRamMb() uint64 {
	if x != nil {
		return x.TotalRamMb
	}
	return 0
}

func (x *NodeStatus) GetAllocatableCpuCores() uint32 {
	if x != nil {
		return x.AllocatableCpuCores
	}
	return 0
}

func (x *NodeStatus) GetAllocatableRamMb() uint64 {
	if x != nil {
		return x.AllocatableRamMb
	}
	return 0
}

func (x *NodeStatus) GetCapabilities() []*NodeCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeStatus) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *NodeStatus) GetHypervisorVersion() string {
	if x != nil {
		return x.HypervisorVersion
	}
	return ""
}

func (x *NodeStatus) GetLastHeartbeatUnix() int64 {
	if x != nil {
		return x.LastHeartbeatUnix
	}
	return 0
}

// Ping response
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Bridge configuration request
type EnsureBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BridgeName    string                 `protobuf:"bytes,1,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`
	Mtu           uint32                 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureBridgeRequest) Reset() {
	*x = EnsureBridgeRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureBridgeRequest) ProtoMessage() {}

func (x *EnsureBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureBridgeRequest.ProtoReflect.Descriptor instead.
func (*EnsureBridgeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *EnsureBridgeRequest) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

func (x *EnsureBridgeRequest) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

// Image import request
type ImageImportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ImageId          string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	SourceUrl        string                 `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	SourceFormat     string                 `protobuf:"bytes,3,opt,name=source_format,json=sourceFormat,proto3" json:"source_format,omitempty"`             // qcow2, raw
	NormalizedFormat string                 `protobuf:"bytes,4,opt,name=normalized_format,json=normalizedFormat,proto3" json:"normalized_format,omitempty"` // raw
	Checksum         string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImageImportRequest) Reset() {
	*x = ImageImportRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageImportRequest) ProtoMessage() {}

func (x *ImageImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageImportRequest.ProtoReflect.Descriptor instead.
func (*ImageImportRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ImageImportRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageImportRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *ImageImportRequest) GetSourceFormat() string {
	if x != nil {
		return x.SourceFormat
	}
	return ""
}

func (x *ImageImportRequest) GetNormalizedFormat() string {
	if x != nil {
		return x.NormalizedFormat
	}
	return ""
}

func (x *ImageImportRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// Volume create request
type VolumeCreateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VolumeId         string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	PoolId           string                 `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	PoolPath         string                 `protobuf:"bytes,3,opt,name=pool_path,json=poolPath,proto3" json:"pool_path,omitempty"`
	Format           string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"` // raw
	SizeBytes        uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	BackingImageId   string                 `protobuf:"bytes,6,opt,name=backing_image_id,json=backingImageId,proto3" json:"backing_image_id,omitempty"`
	BackingImagePath string                 `protobuf:"bytes,7,opt,name=backing_image_path,json=backingImagePath,proto3" json:"backing_image_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VolumeCreateRequest) Reset() {
	*x = VolumeCreateRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeCreateRequest) ProtoMessage() {}

func (x *VolumeCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeCreateRequest.ProtoReflect.Descriptor instead.
func (*VolumeCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeCreateRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *VolumeCreateRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *VolumeCreateRequest) GetPoolPath() string {
	if x != nil {
		return x.PoolPath
	}
	return ""
}

func (x *VolumeCreateRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *VolumeCreateRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *VolumeCreateRequest) GetBackingImageId() string {
	if x != nil {
		return x.BackingImageId
	}
	return ""
}

func (x *VolumeCreateRequest) GetBackingImagePath() string {
	if x != nil {
		return x.BackingImagePath
	}
	return ""
}

// Volume resize request
type VolumeResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	PoolPath      string                 `protobuf:"bytes,2,opt,name=pool_path,json=poolPath,proto3" json:"pool_path,omitempty"`
	NewSizeBytes  uint64                 `protobuf:"varint,3,opt,name=new_size_bytes,json=newSizeBytes,proto3" json:"new_size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeResizeRequest) Reset() {
	*x = VolumeResizeRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeResizeRequest) ProtoMessage() {}

func (x *VolumeResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeResizeRequest.ProtoReflect.Descriptor instead.
func (*VolumeResizeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *VolumeResizeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *VolumeResizeRequest) GetPoolPath() string {
	if x != nil {
		return x.PoolPath
	}
	return ""
}

func (x *VolumeResizeRequest) GetNewSizeBytes() uint64 {
	if x != nil {
		return x.NewSizeBytes
	}
	return 0
}

// Network attachment specification
type NetworkAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	BridgeName    string                 `protobuf:"bytes,2,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Dhcp          bool                   `protobuf:"varint,5,opt,name=dhcp,proto3" json:"dhcp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAttachment) Reset() {
	*x = NetworkAttachment{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAttachment) ProtoMessage() {}

func (x *NetworkAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAttachment.ProtoReflect.Descriptor instead.
func (*NetworkAttachment) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkAttachment) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *NetworkAttachment) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

func (x *NetworkAttachment) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkAttachment) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NetworkAttachment) GetDhcp() bool {
	if x != nil {
		return x.Dhcp
	}
	return false
}

// Disk attachment specification
type DiskAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Bus           string                 `protobuf:"bytes,3,opt,name=bus,proto3" json:"bus,omitempty"` // virtio-blk, virtio-scsi
	Boot          bool                   `protobuf:"varint,4,opt,name=boot,proto3" json:"boot,omitempty"`
	Readonly      bool                   `protobuf:"varint,5,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskAttachment) Reset() {
	*x = DiskAttachment{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskAttachment) ProtoMessage() {}

func (x *DiskAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskAttachment.ProtoReflect.Descriptor instead.
func (*DiskAttachment) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DiskAttachment) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *DiskAttachment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskAttachment) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

func (x *DiskAttachment) GetBoot() bool {
	if x != nil {
		return x.Boot
	}
	return false
}

func (x *DiskAttachment) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

// Boot specification
type BootSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mode             string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // cloud_image, uefi, direct_kernel
	KernelPath       string                 `protobuf:"bytes,2,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	InitrdPath       string                 `protobuf:"bytes,3,opt,name=initrd_path,json=initrdPath,proto3" json:"initrd_path,omitempty"`
	Cmdline          string                 `protobuf:"bytes,4,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	FirmwarePath     string                 `protobuf:"bytes,5,opt,name=firmware_path,json=firmwarePath,proto3" json:"firmware_path,omitempty"`
	BackingImageId   string                 `protobuf:"bytes,6,opt,name=backing_image_id,json=backingImageId,proto3" json:"backing_image_id,omitempty"`       // For cloud_image mode
	BackingImagePath string                 `protobuf:"bytes,7,opt,name=backing_image_path,json=backingImagePath,proto3" json:"backing_image_path,omitempty"` // Actual path to the image file
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BootSpec) Reset() {
	*x = BootSpec{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootSpec) ProtoMessage() {}

func (x *BootSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootSpec.ProtoReflect.Descriptor instead.
func (*BootSpec) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *BootSpec) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *BootSpec) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

func (x *BootSpec) GetInitrdPath() string {
	if x != nil {
		return x.InitrdPath
	}
	return ""
}

func (x *BootSpec) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *BootSpec) GetFirmwarePath() string {
	if x != nil {
		return x.FirmwarePath
	}
	return ""
}

func (x *BootSpec) GetBackingImageId() string {
	if x != nil {
		return x.BackingImageId
	}
	return ""
}

func (x *BootSpec) GetBackingImagePath() string {
	if x != nil {
		return x.BackingImagePath
	}
	return ""
}

// Cloud-init configuration
type CloudInitSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserData      string                 `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	MetaData      string                 `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	NetworkConfig string                 `protobuf:"bytes,3,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudInitSpec) Reset() {
	*x = CloudInitSpec{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInitSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInitSpec) ProtoMessage() {}

func (x *CloudInitSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInitSpec.ProtoReflect.Descriptor instead.
func (*CloudInitSpec) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CloudInitSpec) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *CloudInitSpec) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

func (x *CloudInitSpec) GetNetworkConfig() string {
	if x != nil {
		return x.NetworkConfig
	}
	return ""
}

// VM provisioning request
type ProvisionVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Vcpu          uint32                 `protobuf:"varint,3,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Boot          *BootSpec              `protobuf:"bytes,5,opt,name=boot,proto3" json:"boot,omitempty"`
	Disks         []*DiskAttachment      `protobuf:"bytes,6,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks      []*NetworkAttachment   `protobuf:"bytes,7,rep,name=networks,proto3" json:"networks,omitempty"`
	CloudInit     *CloudInitSpec         `protobuf:"bytes,8,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionVMRequest) Reset() {
	*x = ProvisionVMRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionVMRequest) ProtoMessage() {}

func (x *ProvisionVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionVMRequest.ProtoReflect.Descriptor instead.
func (*ProvisionVMRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ProvisionVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ProvisionVMRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *ProvisionVMRequest) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *ProvisionVMRequest) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ProvisionVMRequest) GetBoot() *BootSpec {
	if x != nil {
		return x.Boot
	}
	return nil
}

func (x *ProvisionVMRequest) GetDisks() []*DiskAttachment {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *ProvisionVMRequest) GetNetworks() []*NetworkAttachment {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ProvisionVMRequest) GetCloudInit() *CloudInitSpec {
	if x != nil {
		return x.CloudInit
	}
	return nil
}

// VM state request/response
type VMStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMStateRequest) Reset() {
	*x = VMStateRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMStateRequest) ProtoMessage() {}

func (x *VMStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMStateRequest.ProtoReflect.Descriptor instead.
func (*VMStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *VMStateRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type VMStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid           string                 `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMStateResponse) Reset() {
	*x = VMStateResponse{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMStateResponse) ProtoMessage() {}

func (x *VMStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMStateResponse.ProtoReflect.Descriptor instead.
func (*VMStateResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *VMStateResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *VMStateResponse) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *VMStateResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

// VM delete request
type VMDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	DeleteVolumes bool                   `protobuf:"varint,2,opt,name=delete_volumes,json=deleteVolumes,proto3" json:"delete_volumes,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMDeleteRequest) Reset() {
	*x = VMDeleteRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMDeleteRequest) ProtoMessage() {}

func (x *VMDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMDeleteRequest.ProtoReflect.Descriptor instead.
func (*VMDeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *VMDeleteRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMDeleteRequest) GetDeleteVolumes() bool {
	if x != nil {
		return x.DeleteVolumes
	}
	return false
}

func (x *VMDeleteRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Node validation response
type NodeValidateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Errors          []*ErrorDetail         `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Kvm             *NodeCapability        `protobuf:"bytes,3,opt,name=kvm,proto3" json:"kvm,omitempty"`
	Kernel          *NodeCapability        `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	CloudHypervisor *NodeCapability        `protobuf:"bytes,5,opt,name=cloud_hypervisor,json=cloudHypervisor,proto3" json:"cloud_hypervisor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeValidateResponse) Reset() {
	*x = NodeValidateResponse{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeValidateResponse) ProtoMessage() {}

func (x *NodeValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeValidateResponse.ProtoReflect.Descriptor instead.
func (*NodeValidateResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *NodeValidateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NodeValidateResponse) GetErrors() []*ErrorDetail {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *NodeValidateResponse) GetKvm() *NodeCapability {
	if x != nil {
		return x.Kvm
	}
	return nil
}

func (x *NodeValidateResponse) GetKernel() *NodeCapability {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *NodeValidateResponse) GetCloudHypervisor() *NodeCapability {
	if x != nil {
		return x.CloudHypervisor
	}
	return nil
}

// Drain mode request
type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *DrainRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *DrainRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ActiveVms     []string               `protobuf:"bytes,2,rep,name=active_vms,json=activeVms,proto3" json:"active_vms,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *DrainResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DrainResponse) GetActiveVms() []string {
	if x != nil {
		return x.ActiveVms
	}
	return nil
}

func (x *DrainResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

// List VMs response
type ListVMsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Vms           []*ListVMsResponse_VMInfo `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ListVMsResponse) GetVms() []*ListVMsResponse_VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

// Console stream request
type ConsoleStreamRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	VmId          string                           `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                                         // VM ID (required in first message)
	Type          ConsoleStreamRequest_MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=chv.agent.v1.ConsoleStreamRequest_MessageType" json:"type,omitempty"` // Message type
	Data          []byte                           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                     // Input data or resize dimensions
	Rows          uint32                           `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`                                                    // Terminal rows (for resize)
	Cols          uint32                           `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`                                                    // Terminal columns (for resize)
	Token         string                           `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`                                                   // Authentication token (first message only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleStreamRequest) Reset() {
	*x = ConsoleStreamRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleStreamRequest) ProtoMessage() {}

func (x *ConsoleStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleStreamRequest.ProtoReflect.Descriptor instead.
func (*ConsoleStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ConsoleStreamRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ConsoleStreamRequest) GetType() ConsoleStreamRequest_MessageType {
	if x != nil {
		return x.Type
	}
	return ConsoleStreamRequest_UNKNOWN
}

func (x *ConsoleStreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConsoleStreamRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ConsoleStreamRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ConsoleStreamRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Console stream response
type ConsoleStreamResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Type          ConsoleStreamResponse_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=chv.agent.v1.ConsoleStreamResponse_MessageType" json:"type,omitempty"`
	Data          []byte                            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`            // Output data
	Message       string                            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`      // Error or status message
	Timestamp     int64                             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleStreamResponse) Reset() {
	*x = ConsoleStreamResponse{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleStreamResponse) ProtoMessage() {}

func (x *ConsoleStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleStreamResponse.ProtoReflect.Descriptor instead.
func (*ConsoleStreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ConsoleStreamResponse) GetType() ConsoleStreamResponse_MessageType {
	if x != nil {
		return x.Type
	}
	return ConsoleStreamResponse_UNKNOWN
}

func (x *ConsoleStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConsoleStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConsoleStreamResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Console status request
type ConsoleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleStatusRequest) Reset() {
	*x = ConsoleStatusRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleStatusRequest) ProtoMessage() {}

func (x *ConsoleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleStatusRequest.ProtoReflect.Descriptor instead.
func (*ConsoleStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ConsoleStatusRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// Console status response
type ConsoleStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	ClientCount   int32                  `protobuf:"varint,4,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	LogPath       string                 `protobuf:"bytes,5,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	TtyEnabled    bool                   `protobuf:"varint,6,opt,name=tty_enabled,json=ttyEnabled,proto3" json:"tty_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleStatusResponse) Reset() {
	*x = ConsoleStatusResponse{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleStatusResponse) ProtoMessage() {}

func (x *ConsoleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleStatusResponse.ProtoReflect.Descriptor instead.
func (*ConsoleStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{24}
}

func (x *ConsoleStatusResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ConsoleStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ConsoleStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ConsoleStatusResponse) GetClientCount() int32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *ConsoleStatusResponse) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *ConsoleStatusResponse) GetTtyEnabled() bool {
	if x != nil {
		return x.TtyEnabled
	}
	return false
}

// Console close request
type ConsoleCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleCloseRequest) Reset() {
	*x = ConsoleCloseRequest{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCloseRequest) ProtoMessage() {}

func (x *ConsoleCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCloseRequest.ProtoReflect.Descriptor instead.
func (*ConsoleCloseRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ConsoleCloseRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ConsoleCloseRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Console close response
type ConsoleCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Closed        bool                   `protobuf:"varint,2,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleCloseResponse) Reset() {
	*x = ConsoleCloseResponse{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCloseResponse) ProtoMessage() {}

func (x *ConsoleCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCloseResponse.ProtoReflect.Descriptor instead.
func (*ConsoleCloseResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{26}
}

func (x *ConsoleCloseResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ConsoleCloseResponse) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type ListVMsResponse_VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid           string                 `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Vcpu          uint32                 `protobuf:"varint,4,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse_VMInfo) Reset() {
	*x = ListVMsResponse_VMInfo{}
	mi := &file_internal_pb_agent_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse_VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse_VMInfo) ProtoMessage() {}

func (x *ListVMsResponse_VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agent_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse_VMInfo.ProtoReflect.Descriptor instead.
func (*ListVMsResponse_VMInfo) Descriptor() ([]byte, []int) {
	return file_internal_pb_agent_agent_proto_rawDescGZIP(), []int{20, 0}
}

func (x *ListVMsResponse_VMInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ListVMsResponse_VMInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ListVMsResponse_VMInfo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ListVMsResponse_VMInfo) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *ListVMsResponse_VMInfo) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

var File_internal_pb_agent_agent_proto protoreflect.FileDescriptor

const file_internal_pb_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/pb/agent/agent.proto\x12\fchv.agent.v1\"\a\n" +
	"\x05Empty\"m\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\"8\n" +
	"\x0eNodeCapability\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc9\x03\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12&\n" +
	"\x0ftotal_cpu_cores\x18\x04 \x01(\rR\rtotalCpuCores\x12 \n" +
	"\ftotal_ram_mb\x18\x05 \x01(\x04R\n" +
	"totalRamMb\x122\n" +
	"\x15allocatable_cpu_cores\x18\x06 \x01(\rR\x13allocatableCpuCores\x12,\n" +
	"\x12allocatable_ram_mb\x18\a \x01(\x04R\x10allocatableRamMb\x12@\n" +
	"\fcapabilities\x18\b \x03(\v2\x1c.chv.agent.v1.NodeCapabilityR\fcapabilities\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\x12-\n" +
	"\x12hypervisor_version\x18\n" +
	" \x01(\tR\x11hypervisorVersion\x12.\n" +
	"\x13last_heartbeat_unix\x18\v \x01(\x03R\x11lastHeartbeatUnix\"8\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"H\n" +
	"\x13EnsureBridgeRequest\x12\x1f\n" +
	"\vbridge_name\x18\x01 \x01(\tR\n" +
	"bridgeName\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\rR\x03mtu\"\xbc\x01\n" +
	"\x12ImageImportRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"source_url\x18\x02 \x01(\tR\tsourceUrl\x12#\n" +
	"\rsource_format\x18\x03 \x01(\tR\fsourceFormat\x12+\n" +
	"\x11normalized_format\x18\x04 \x01(\tR\x10normalizedFormat\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\"\xf7\x01\n" +
	"\x13VolumeCreateRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\x12\x1b\n" +
	"\tpool_path\x18\x03 \x01(\tR\bpoolPath\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\x12(\n" +
	"\x10backing_image_id\x18\x06 \x01(\tR\x0ebackingImageId\x12,\n" +
	"\x12backing_image_path\x18\a \x01(\tR\x10backingImagePath\"u\n" +
	"\x13VolumeResizeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1b\n" +
	"\tpool_path\x18\x02 \x01(\tR\bpoolPath\x12$\n" +
	"\x0enew_size_bytes\x18\x03 \x01(\x04R\fnewSizeBytes\"\xa7\x01\n" +
	"\x11NetworkAttachment\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x1f\n" +
	"\vbridge_name\x18\x02 \x01(\tR\n" +
	"bridgeName\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04dhcp\x18\x05 \x01(\bR\x04dhcp\"\x83\x01\n" +
	"\x0eDiskAttachment\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x10\n" +
	"\x03bus\x18\x03 \x01(\tR\x03bus\x12\x12\n" +
	"\x04boot\x18\x04 \x01(\bR\x04boot\x12\x1a\n" +
	"\breadonly\x18\x05 \x01(\bR\breadonly\"\xf7\x01\n" +
	"\bBootSpec\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1f\n" +
	"\vkernel_path\x18\x02 \x01(\tR\n" +
	"kernelPath\x12\x1f\n" +
	"\vinitrd_path\x18\x03 \x01(\tR\n" +
	"initrdPath\x12\x18\n" +
	"\acmdline\x18\x04 \x01(\tR\acmdline\x12#\n" +
	"\rfirmware_path\x18\x05 \x01(\tR\ffirmwarePath\x12(\n" +
	"\x10backing_image_id\x18\x06 \x01(\tR\x0ebackingImageId\x12,\n" +
	"\x12backing_image_path\x18\a \x01(\tR\x10backingImagePath\"p\n" +
	"\rCloudInitSpec\x12\x1b\n" +
	"\tuser_data\x18\x01 \x01(\tR\buserData\x12\x1b\n" +
	"\tmeta_data\x18\x02 \x01(\tR\bmetaData\x12%\n" +
	"\x0enetwork_config\x18\x03 \x01(\tR\rnetworkConfig\"\xcc\x02\n" +
	"\x12ProvisionVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12\x12\n" +
	"\x04vcpu\x18\x03 \x01(\rR\x04vcpu\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x04R\bmemoryMb\x12*\n" +
	"\x04boot\x18\x05 \x01(\v2\x16.chv.agent.v1.BootSpecR\x04boot\x122\n" +
	"\x05disks\x18\x06 \x03(\v2\x1c.chv.agent.v1.DiskAttachmentR\x05disks\x12;\n" +
	"\bnetworks\x18\a \x03(\v2\x1f.chv.agent.v1.NetworkAttachmentR\bnetworks\x12:\n" +
	"\n" +
	"cloud_init\x18\b \x01(\v2\x1b.chv.agent.v1.CloudInitSpecR\tcloudInit\"%\n" +
	"\x0eVMStateRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x7f\n" +
	"\x0fVMStateResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\tR\x03pid\x12/\n" +
	"\x05error\x18\x04 \x01(\v2\x19.chv.agent.v1.ErrorDetailR\x05error\"c\n" +
	"\x0fVMDeleteRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12%\n" +
	"\x0edelete_volumes\x18\x02 \x01(\bR\rdeleteVolumes\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x88\x02\n" +
	"\x14NodeValidateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\x06errors\x18\x02 \x03(\v2\x19.chv.agent.v1.ErrorDetailR\x06errors\x12.\n" +
	"\x03kvm\x18\x03 \x01(\v2\x1c.chv.agent.v1.NodeCapabilityR\x03kvm\x124\n" +
	"\x06kernel\x18\x04 \x01(\v2\x1c.chv.agent.v1.NodeCapabilityR\x06kernel\x12G\n" +
	"\x10cloud_hypervisor\x18\x05 \x01(\v2\x1c.chv.agent.v1.NodeCapabilityR\x0fcloudHypervisor\"<\n" +
	"\fDrainRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"o\n" +
	"\rDrainResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"active_vms\x18\x02 \x03(\tR\tactiveVms\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.chv.agent.v1.ErrorDetailR\x05error\"\xc1\x01\n" +
	"\x0fListVMsResponse\x126\n" +
	"\x03vms\x18\x01 \x03(\v2$.chv.agent.v1.ListVMsResponse.VMInfoR\x03vms\x1av\n" +
	"\x06VMInfo\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\tR\x03pid\x12\x12\n" +
	"\x04vcpu\x18\x04 \x01(\rR\x04vcpu\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x04R\bmemoryMb\"\xfe\x01\n" +
	"\x14ConsoleStreamRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12B\n" +
	"\x04type\x18\x02 \x01(\x0e2..chv.agent.v1.ConsoleStreamRequest.MessageTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\rR\x04cols\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\";\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05INPUT\x10\x01\x12\n" +
	"\n" +
	"\x06RESIZE\x10\x02\x12\b\n" +
	"\x04PING\x10\x03\"\xf4\x01\n" +
	"\x15ConsoleStreamResponse\x12C\n" +
	"\x04type\x18\x01 \x01(\x0e2/.chv.agent.v1.ConsoleStreamResponse.MessageTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"J\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06OUTPUT\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\n" +
	"\n" +
	"\x06STATUS\x10\x03\x12\v\n" +
	"\aHISTORY\x10\x04\"+\n" +
	"\x14ConsoleStatusRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\xc1\x01\n" +
	"\x15ConsoleStatusResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\x12!\n" +
	"\fclient_count\x18\x04 \x01(\x05R\vclientCount\x12\x19\n" +
	"\blog_path\x18\x05 \x01(\tR\alogPath\x12\x1f\n" +
	"\vtty_enabled\x18\x06 \x01(\bR\n" +
	"ttyEnabled\"@\n" +
	"\x13ConsoleCloseRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"C\n" +
	"\x14ConsoleCloseResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x16\n" +
	"\x06closed\x18\x02 \x01(\bR\x06closed2\xdf\v\n" +
	"\fAgentService\x127\n" +
	"\x04Ping\x12\x13.chv.agent.v1.Empty\x1a\x1a.chv.agent.v1.PingResponse\x12A\n" +
	"\x10ReportNodeStatus\x12\x13.chv.agent.v1.Empty\x1a\x18.chv.agent.v1.NodeStatus\x12G\n" +
	"\fValidateNode\x12\x13.chv.agent.v1.Empty\x1a\".chv.agent.v1.NodeValidateResponse\x12U\n" +
	"\fEnsureBridge\x12!.chv.agent.v1.EnsureBridgeRequest\x1a\".chv.agent.v1.NodeValidateResponse\x12S\n" +
	"\vImportImage\x12 .chv.agent.v1.ImageImportRequest\x1a\".chv.agent.v1.NodeValidateResponse\x12U\n" +
	"\fCreateVolume\x12!.chv.agent.v1.VolumeCreateRequest\x1a\".chv.agent.v1.NodeValidateResponse\x12U\n" +
	"\fResizeVolume\x12!.chv.agent.v1.VolumeResizeRequest\x1a\".chv.agent.v1.NodeValidateResponse\x12U\n" +
	"\fDeleteVolume\x12!.chv.agent.v1.VolumeCreateRequest\x1a\".chv.agent.v1.NodeValidateResponse\x12N\n" +
	"\vProvisionVM\x12 .chv.agent.v1.ProvisionVMRequest\x1a\x1d.chv.agent.v1.VMStateResponse\x12F\n" +
	"\aStartVM\x12\x1c.chv.agent.v1.VMStateRequest\x1a\x1d.chv.agent.v1.VMStateResponse\x12E\n" +
	"\x06StopVM\x12\x1c.chv.agent.v1.VMStateRequest\x1a\x1d.chv.agent.v1.VMStateResponse\x12G\n" +
	"\bRebootVM\x12\x1c.chv.agent.v1.VMStateRequest\x1a\x1d.chv.agent.v1.VMStateResponse\x12H\n" +
	"\bDeleteVM\x12\x1d.chv.agent.v1.VMDeleteRequest\x1a\x1d.chv.agent.v1.VMStateResponse\x12I\n" +
	"\n" +
	"GetVMState\x12\x1c.chv.agent.v1.VMStateRequest\x1a\x1d.chv.agent.v1.VMStateResponse\x12A\n" +
	"\vListHostVMs\x12\x13.chv.agent.v1.Empty\x1a\x1d.chv.agent.v1.ListVMsResponse\x12G\n" +
	"\fPrepareDrain\x12\x1a.chv.agent.v1.DrainRequest\x1a\x1b.chv.agent.v1.DrainResponse\x12\\\n" +
	"\rStreamConsole\x12\".chv.agent.v1.ConsoleStreamRequest\x1a#.chv.agent.v1.ConsoleStreamResponse(\x010\x01\x12[\n" +
	"\x10GetConsoleStatus\x12\".chv.agent.v1.ConsoleStatusRequest\x1a#.chv.agent.v1.ConsoleStatusResponse\x12U\n" +
	"\fCloseConsole\x12!.chv.agent.v1.ConsoleCloseRequest\x1a\".chv.agent.v1.ConsoleCloseResponseB,Z*github.com/chv/chv/internal/pb/agent;agentb\x06proto3"

var (
	file_internal_pb_agent_agent_proto_rawDescOnce sync.Once
	file_internal_pb_agent_agent_proto_rawDescData []byte
)

func file_internal_pb_agent_agent_proto_rawDescGZIP() []byte {
	file_internal_pb_agent_agent_proto_rawDescOnce.Do(func() {
		file_internal_pb_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_agent_agent_proto_rawDesc), len(file_internal_pb_agent_agent_proto_rawDesc)))
	})
	return file_internal_pb_agent_agent_proto_rawDescData
}

var file_internal_pb_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_pb_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_internal_pb_agent_agent_proto_goTypes = []any{
	(ConsoleStreamRequest_MessageType)(0),  // 0: chv.agent.v1.ConsoleStreamRequest.MessageType
	(ConsoleStreamResponse_MessageType)(0), // 1: chv.agent.v1.ConsoleStreamResponse.MessageType
	(*Empty)(nil),                          // 2: chv.agent.v1.Empty
	(*ErrorDetail)(nil),                    // 3: chv.agent.v1.ErrorDetail
	(*NodeCapability)(nil),                 // 4: chv.agent.v1.NodeCapability
	(*NodeStatus)(nil),                     // 5: chv.agent.v1.NodeStatus
	(*PingResponse)(nil),                   // 6: chv.agent.v1.PingResponse
	(*EnsureBridgeRequest)(nil),            // 7: chv.agent.v1.EnsureBridgeRequest
	(*ImageImportRequest)(nil),             // 8: chv.agent.v1.ImageImportRequest
	(*VolumeCreateRequest)(nil),            // 9: chv.agent.v1.VolumeCreateRequest
	(*VolumeResizeRequest)(nil),            // 10: chv.agent.v1.VolumeResizeRequest
	(*NetworkAttachment)(nil),              // 11: chv.agent.v1.NetworkAttachment
	(*DiskAttachment)(nil),                 // 12: chv.agent.v1.DiskAttachment
	(*BootSpec)(nil),                       // 13: chv.agent.v1.BootSpec
	(*CloudInitSpec)(nil),                  // 14: chv.agent.v1.CloudInitSpec
	(*ProvisionVMRequest)(nil),             // 15: chv.agent.v1.ProvisionVMRequest
	(*VMStateRequest)(nil),                 // 16: chv.agent.v1.VMStateRequest
	(*VMStateResponse)(nil),                // 17: chv.agent.v1.VMStateResponse
	(*VMDeleteRequest)(nil),                // 18: chv.agent.v1.VMDeleteRequest
	(*NodeValidateResponse)(nil),           // 19: chv.agent.v1.NodeValidateResponse
	(*DrainRequest)(nil),                   // 20: chv.agent.v1.DrainRequest
	(*DrainResponse)(nil),                  // 21: chv.agent.v1.DrainResponse
	(*ListVMsResponse)(nil),                // 22: chv.agent.v1.ListVMsResponse
	(*ConsoleStreamRequest)(nil),           // 23: chv.agent.v1.ConsoleStreamRequest
	(*ConsoleStreamResponse)(nil),          // 24: chv.agent.v1.ConsoleStreamResponse
	(*ConsoleStatusRequest)(nil),           // 25: chv.agent.v1.ConsoleStatusRequest
	(*ConsoleStatusResponse)(nil),          // 26: chv.agent.v1.ConsoleStatusResponse
	(*ConsoleCloseRequest)(nil),            // 27: chv.agent.v1.ConsoleCloseRequest
	(*ConsoleCloseResponse)(nil),           // 28: chv.agent.v1.ConsoleCloseResponse
	(*ListVMsResponse_VMInfo)(nil),         // 29: chv.agent.v1.ListVMsResponse.VMInfo
}
var file_internal_pb_agent_agent_proto_depIdxs = []int32{
	4,  // 0: chv.agent.v1.NodeStatus.capabilities:type_name -> chv.agent.v1.NodeCapability
	13, // 1: chv.agent.v1.ProvisionVMRequest.boot:type_name -> chv.agent.v1.BootSpec
	12, // 2: chv.agent.v1.ProvisionVMRequest.disks:type_name -> chv.agent.v1.DiskAttachment
	11, // 3: chv.agent.v1.ProvisionVMRequest.networks:type_name -> chv.agent.v1.NetworkAttachment
	14, // 4: chv.agent.v1.ProvisionVMRequest.cloud_init:type_name -> chv.agent.v1.CloudInitSpec
	3,  // 5: chv.agent.v1.VMStateResponse.error:type_name -> chv.agent.v1.ErrorDetail
	3,  // 6: chv.agent.v1.NodeValidateResponse.errors:type_name -> chv.agent.v1.ErrorDetail
	4,  // 7: chv.agent.v1.NodeValidateResponse.kvm:type_name -> chv.agent.v1.NodeCapability
	4,  // 8: chv.agent.v1.NodeValidateResponse.kernel:type_name -> chv.agent.v1.NodeCapability
	4,  // 9: chv.agent.v1.NodeValidateResponse.cloud_hypervisor:type_name -> chv.agent.v1.NodeCapability
	3,  // 10: chv.agent.v1.DrainResponse.error:type_name -> chv.agent.v1.ErrorDetail
	29, // 11: chv.agent.v1.ListVMsResponse.vms:type_name -> chv.agent.v1.ListVMsResponse.VMInfo
	0,  // 12: chv.agent.v1.ConsoleStreamRequest.type:type_name -> chv.agent.v1.ConsoleStreamRequest.MessageType
	1,  // 13: chv.agent.v1.ConsoleStreamResponse.type:type_name -> chv.agent.v1.ConsoleStreamResponse.MessageType
	2,  // 14: chv.agent.v1.AgentService.Ping:input_type -> chv.agent.v1.Empty
	2,  // 15: chv.agent.v1.AgentService.ReportNodeStatus:input_type -> chv.agent.v1.Empty
	2,  // 16: chv.agent.v1.AgentService.ValidateNode:input_type -> chv.agent.v1.Empty
	7,  // 17: chv.agent.v1.AgentService.EnsureBridge:input_type -> chv.agent.v1.EnsureBridgeRequest
	8,  // 18: chv.agent.v1.AgentService.ImportImage:input_type -> chv.agent.v1.ImageImportRequest
	9,  // 19: chv.agent.v1.AgentService.CreateVolume:input_type -> chv.agent.v1.VolumeCreateRequest
	10, // 20: chv.agent.v1.AgentService.ResizeVolume:input_type -> chv.agent.v1.VolumeResizeRequest
	9,  // 21: chv.agent.v1.AgentService.DeleteVolume:input_type -> chv.agent.v1.VolumeCreateRequest
	15, // 22: chv.agent.v1.AgentService.ProvisionVM:input_type -> chv.agent.v1.ProvisionVMRequest
	16, // 23: chv.agent.v1.AgentService.StartVM:input_type -> chv.agent.v1.VMStateRequest
	16, // 24: chv.agent.v1.AgentService.StopVM:input_type -> chv.agent.v1.VMStateRequest
	16, // 25: chv.agent.v1.AgentService.RebootVM:input_type -> chv.agent.v1.VMStateRequest
	18, // 26: chv.agent.v1.AgentService.DeleteVM:input_type -> chv.agent.v1.VMDeleteRequest
	16, // 27: chv.agent.v1.AgentService.GetVMState:input_type -> chv.agent.v1.VMStateRequest
	2,  // 28: chv.agent.v1.AgentService.ListHostVMs:input_type -> chv.agent.v1.Empty
	20, // 29: chv.agent.v1.AgentService.PrepareDrain:input_type -> chv.agent.v1.DrainRequest
	23, // 30: chv.agent.v1.AgentService.StreamConsole:input_type -> chv.agent.v1.ConsoleStreamRequest
	25, // 31: chv.agent.v1.AgentService.GetConsoleStatus:input_type -> chv.agent.v1.ConsoleStatusRequest
	27, // 32: chv.agent.v1.AgentService.CloseConsole:input_type -> chv.agent.v1.ConsoleCloseRequest
	6,  // 33: chv.agent.v1.AgentService.Ping:output_type -> chv.agent.v1.PingResponse
	5,  // 34: chv.agent.v1.AgentService.ReportNodeStatus:output_type -> chv.agent.v1.NodeStatus
	19, // 35: chv.agent.v1.AgentService.ValidateNode:output_type -> chv.agent.v1.NodeValidateResponse
	19, // 36: chv.agent.v1.AgentService.EnsureBridge:output_type -> chv.agent.v1.NodeValidateResponse
	19, // 37: chv.agent.v1.AgentService.ImportImage:output_type -> chv.agent.v1.NodeValidateResponse
	19, // 38: chv.agent.v1.AgentService.CreateVolume:output_type -> chv.agent.v1.NodeValidateResponse
	19, // 39: chv.agent.v1.AgentService.ResizeVolume:output_type -> chv.agent.v1.NodeValidateResponse
	19, // 40: chv.agent.v1.AgentService.DeleteVolume:output_type -> chv.agent.v1.NodeValidateResponse
	17, // 41: chv.agent.v1.AgentService.ProvisionVM:output_type -> chv.agent.v1.VMStateResponse
	17, // 42: chv.agent.v1.AgentService.StartVM:output_type -> chv.agent.v1.VMStateResponse
	17, // 43: chv.agent.v1.AgentService.StopVM:output_type -> chv.agent.v1.VMStateResponse
	17, // 44: chv.agent.v1.AgentService.RebootVM:output_type -> chv.agent.v1.VMStateResponse
	17, // 45: chv.agent.v1.AgentService.DeleteVM:output_type -> chv.agent.v1.VMStateResponse
	17, // 46: chv.agent.v1.AgentService.GetVMState:output_type -> chv.agent.v1.VMStateResponse
	22, // 47: chv.agent.v1.AgentService.ListHostVMs:output_type -> chv.agent.v1.ListVMsResponse
	21, // 48: chv.agent.v1.AgentService.PrepareDrain:output_type -> chv.agent.v1.DrainResponse
	24, // 49: chv.agent.v1.AgentService.StreamConsole:output_type -> chv.agent.v1.ConsoleStreamResponse
	26, // 50: chv.agent.v1.AgentService.GetConsoleStatus:output_type -> chv.agent.v1.ConsoleStatusResponse
	28, // 51: chv.agent.v1.AgentService.CloseConsole:output_type -> chv.agent.v1.ConsoleCloseResponse
	33, // [33:52] is the sub-list for method output_type
	14, // [14:33] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_internal_pb_agent_agent_proto_init() }
func file_internal_pb_agent_agent_proto_init() {
	if File_internal_pb_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_agent_agent_proto_rawDesc), len(file_internal_pb_agent_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_agent_agent_proto_goTypes,
		DependencyIndexes: file_internal_pb_agent_agent_proto_depIdxs,
		EnumInfos:         file_internal_pb_agent_agent_proto_enumTypes,
		MessageInfos:      file_internal_pb_agent_agent_proto_msgTypes,
	}.Build()
	File_internal_pb_agent_agent_proto = out.File
	file_internal_pb_agent_agent_proto_goTypes = nil
	file_internal_pb_agent_agent_proto_depIdxs = nil
}
