[package]
name = "chv-controlplane-store"
version = "0.2.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
test-util = []

[dependencies]
chv-common = { path = "../chv-common" }
chv-controlplane-types = { path = "../chv-controlplane-types" }
aes-gcm = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
hex = { workspace = true }
metrics = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true, default-features = false, features = ["uuid", "chrono"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
